apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
      - name: wait-for-cloud-config
        image: curlimages/curl:8.8.0
        command: ['sh', '-c', 'until curl -s http://cloud-config:9296/actuator/health | grep UP; do echo waiting for cloud-config; sleep 3; done']

      containers:
        - name: api-gateway
          image: {{ index .Values.services "api-gateway" "image" "repository" }}:{{ index .Values.services "api-gateway" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "api-gateway" "service" "port" }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: api-gateway
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            - name: EUREKA_CLIENT_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_REGION
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_MYZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
      restartPolicy: Always
