apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  labels:
    app: cloud-config
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: cloud-config
          image: {{ index .Values.services "cloud-config" "image" "repository" }}:{{ index .Values.services "cloud-config" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "cloud-config" "service" "port" }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            {{- range $key, $value := .Values.commonEnv }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: EUREKA_INSTANCE_HOSTNAME
              value: cloud-config
      restartPolicy: Always
