apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config
  labels:
    app: cloud-config
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: cloud-config
  template:
    metadata:
      labels:
        app: cloud-config
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox:1.36
          command: ['sh', '-c', 'until wget -q --spider http://service-discovery:{{ index .Values.services "service-discovery" "service" "port" }}/actuator/health; do echo waiting for service-discovery; sleep 5; done']

      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot | default true }}
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
      containers:
        - name: cloud-config
          image: {{ index .Values.services "cloud-config" "image" "repository" }}:{{ index .Values.services "cloud-config" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "cloud-config" "service" "port" }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
            runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9296
            initialDelaySeconds: 10
            periodSeconds: 5

          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "https://github.com/ecommerce-microservice-Devops-project/cloud-configs.git"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: cloud-config
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            - name: EUREKA_CLIENT_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_REGION
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_MYZONE
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS

      restartPolicy: Always
