apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  labels:
    app: cloud-config
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values.services "cloud-config" "service" "port" }}
      targetPort: {{ index .Values.services "cloud-config" "service" "port" }}
  selector:
    app: cloud-config
