apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  labels:
    app: favourite-service
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values.services "favourite-service" "service" "port" }}
      targetPort: {{ index .Values.services "favourite-service" "service" "port" }}
  selector:
    app: favourite-service
