apiVersion: apps/v1
kind: Deployment
metadata:
  name: favourite-service
  labels:
    app: favourite-service
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: favourite-service
  template:
    metadata:
      labels:
        app: favourite-service
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot | default true }}
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
      containers:
        - name: favourite-service
          image: {{ index .Values.services "favourite-service" "image" "repository" }}:{{ index .Values.services "favourite-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "favourite-service" "service" "port" }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
            runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: favourite-service
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            - name: EUREKA_CLIENT_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_REGION
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_MYZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          volumeMounts:
            - name: h2-volume
              mountPath: /data/h2
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: favourite-service-h2-pvc
      restartPolicy: Always
