apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    pod-security.kubernetes.io/enforce: "restricted"
    pod-security.kubernetes.io/warn: "baseline"
    pod-security.kubernetes.io/audit: "baseline"
