apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-core-to-all
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: core
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-business-traffic
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      tier: business
  ingress:
  - from:
    - podSelector:
        matchLabels:
          tier: business
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-to-service-discovery
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: service-discovery
  ingress:
  - from:
    - podSelector: {}  # Permitir a todos los pods del namespace
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-to-zipkin
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: zipkin
  ingress:
    - from:
        - podSelector: {}  # permite de todos los pods del namespace
  policyTypes:
    - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-namespace
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector: {}  # Aplica a todos los pods del namespace
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          purpose: observability
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-proxy
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: proxy-client
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-to-business
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      tier: business
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: proxy-client
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-api
  namespace: {{ .Values.global.namespace }}
spec:
  podSelector:
    matchLabels:
      app: api-gateway
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
      podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
