apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ index .Values.services "order-service" "service" "port" }}
      targetPort: {{ index .Values.services "order-service" "service" "port" }}
  selector:
    app: order-service
