apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values.services "product-service" "service" "port" }}
      targetPort: {{ index .Values.services "product-service" "service" "port" }}
  selector:
    app: product-service
