apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        io.kompose.network/microservices_network: "true"
    spec:
      initContainers:
      - name: wait-for-cloud-config
        image: curlimages/curl:8.8.0
        command: ['sh', '-c', 'until curl -s http://cloud-config:9296/actuator/health | grep UP; do echo waiting for cloud-config; sleep 3; done']
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot | default true }}
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
      containers:
        - name: product-service
          image: {{ index .Values.services "product-service" "image" "repository" }}:{{ index .Values.services "product-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "product-service" "service" "port" }} 
          resources: {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
            runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: product-service
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            - name: EUREKA_CLIENT_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_REGION
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_MYZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          volumeMounts:
            - name: h2-volume
              mountPath: /data/h2
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: product-service-h2-pvc
      restartPolicy: Always
