apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values.services "proxy-client" "service" "port" }}
      targetPort: {{ index .Values.services "proxy-client" "service" "port" }}
  selector:
    app: proxy-client
