apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-discovery-monitor
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: service-discovery
  namespaceSelector:
    matchNames:
    - ecommerce-develop
    - ecommerce-stage
    - ecommerce-master
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
