apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  labels:
    app: service-discovery
    role: core
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
        role: core
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot | default true }}
        runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
        runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
        fsGroup: {{ .Values.securityContext.fsGroup | default 1000 }}
      containers:

        - name: service-discovery
          image: {{ index .Values.services "service-discovery" "image" "repository" }}:{{ index .Values.services "service-discovery" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "service-discovery" "service" "port" }} 
          resources: {{- toYaml (index .Values.services "service-discovery" "resources") | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ index .Values.services "service-discovery" "service" "port" }}
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ index .Values.services "service-discovery" "service" "port" }}
            initialDelaySeconds: 10
            periodSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser | default 1000 }}
            runAsGroup: {{ .Values.securityContext.runAsGroup | default 1000 }}
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
      restartPolicy: Always
