apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ index .Values.services "service-discovery" "service" "port" }}
      targetPort: {{ index .Values.services "service-discovery" "service" "port" }}
  selector:
    app: service-discovery
