apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:

        - name: service-discovery
          image: {{ index .Values.services "service-discovery" "image" "repository" }}:{{ index .Values.services "service-discovery" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "service-discovery" "service" "port" }}
<<<<<<< HEAD
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ index .Values.services "service-discovery" "service" "port" }}
            initialDelaySeconds: 20
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ index .Values.services "service-discovery" "service" "port" }}
            initialDelaySeconds: 10
            periodSeconds: 5
=======
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
>>>>>>> 0f8075a5a9b7a8c66e4712150e4b9f9e04cbf0d3
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
      restartPolicy: Always
