apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ index .Values.services "shipping-service" "service" "port" }}
      targetPort: {{ index .Values.services "shipping-service" "service" "port" }}
  selector:
    app: shipping-service
