apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: user-service
          image: {{ index .Values.services "user-service" "image" "repository" }}:{{ index .Values.services "user-service" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "user-service" "service" "port" }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
            - name: EUREKA_CLIENT_REGION
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_REGION
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_CLIENT_SERVICEURL_MYZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_CONFIG_IMPORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_ZIPKIN_BASE-URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: SPRING_ZIPKIN_BASE-URL
            - name: EUREKA_INSTANCE_HOSTNAME
              value: user-service
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-common-env
                  key: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          volumeMounts:
            - name: h2-volume
              mountPath: /data/h2
      volumes:
        - name: h2-volume
          persistentVolumeClaim:
            claimName: user-service-h2-pvc
      restartPolicy: Always
