apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values.services "user-service" "service" "port" }}
      targetPort: {{ index .Values.services "user-service" "service" "port" }}
  selector:
    app: user-service
