apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: ClusterIP
  ports:
    - port: {{ index .Values.services "zipkin" "service" "port" }}
      targetPort: {{ index .Values.services "zipkin" "service" "port" }}
  selector:
    app: zipkin
