apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  replicas: {{ .Values.defaults.replicas }}
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: {{ index .Values.services "zipkin" "image" "repository" }}:{{ index .Values.services "zipkin" "image" "tag" }}
          ports:
            - containerPort: {{ index .Values.services "zipkin" "service" "port" }}
          resources: {}
      restartPolicy: Always
