apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-core-to-all
  namespace: ecommerce-develop
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          role: core
