apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-proxy
  namespace: ecommerce-develop
spec:
  podSelector:
    matchLabels:
      app: proxy-client
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: api-gateway
