apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-proxy-to-business
  namespace: ecommerce-develop
spec:
  podSelector:
    matchLabels:
      tier: business
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: proxy-client
