apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: full-access-between-services
  namespace: ecommerce-dev
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - user-service
          - product-service
          - order-service
          - payment-service
          - favourite-service
          - shipping-service
          - proxy-client
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - user-service
                  - product-service
                  - order-service
                  - payment-service
                  - favourite-service
                  - shipping-service
                  - proxy-client
