apiVersion: v2
name: kube-prometheus-stack
description: Helm chart for deploying Prometheus Operator, Prometheus, Grafana and CRDs
type: application
version: 73.2.3
appVersion: v0.83.0

dependencies:
  - name: kube-prometheus-stack
    version: "73.2.3"
    repository: "https://prometheus-community.github.io/helm-charts"
