apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.services.api-gateway.service.port }}
      targetPort: {{ .Values.services.api-gateway.service.port }}
      protocol: TCP
      name: http
  selector:
    app: api-gateway
