apiVersion: v1
kind: Service
metadata:
  name: cloud-config
  labels:
    app: cloud-config
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.services.cloud-config.service.port }}
      targetPort: {{ .Values.services.cloud-config.service.port }}
  selector:
    app: cloud-config
