apiVersion: v1
kind: Service
metadata:
  name: favourite-service
  labels:
    app: favourite-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.services.favourite-service.service.port }}
      targetPort: {{ .Values.services.favourite-service.service.port }}
  selector:
    app: favourite-service
