apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.services.order-service.service.port }}
      targetPort: {{ .Values.services.order-service.service.port }}
  selector:
    app: order-service
