apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.services.payment-service.service.port }}
      targetPort: {{ .Values.services.payment-service.service.port }}
  selector:
    app: payment-service
