apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  replicas: {{ .Values.services.product-service.replicaCount }}
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
        io.kompose.network/microservices_network: "true"
    spec:
      containers:
        - name: product-service
          image: "{{ .Values.services.product-service.image.repository }}:{{ .Values.services.product-service.image.tag }}"
          ports:
            - containerPort: {{ .Values.services.product-service.service.port }}
          env:
            - name: EUREKA_CLIENT_AVAILABILITYZONES_DEFAULT
              value: myzone
            - name: EUREKA_CLIENT_REGION
              value: default
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-discovery-container:8761/eureka/
            - name: EUREKA_CLIENT_SERVICEURL_MYZONE
              value: http://service-discovery-container:8761/eureka
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://cloud-config-container:9296/
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_ZIPKIN_BASE-URL
              value: http://zipkin:9411
            - name: EUREKA_INSTANCE_HOSTNAME
              value: product-service
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          resources: {{- toYaml .Values.services.product-service.resources | nindent 12 }}
      restartPolicy: Always
