apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.services.product-service.service.port }}
      targetPort: {{ .Values.services.product-service.service.port }}
  selector:
    app: product-service
