apiVersion: v1
kind: Service
metadata:
  name: proxy-client
  labels:
    app: proxy-client
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.proxyClient.service.port }}
      targetPort: {{ .Values.proxyClient.containerPort }}
  selector:
    app: proxy-client
