apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  labels:
    app: service-discovery
spec:
  type: {{ .Values.serviceDiscovery.service.type }}
  ports:
    - name: "http"
      port: {{ .Values.serviceDiscovery.service.port }}
      targetPort: {{ .Values.serviceDiscovery.containerPort }}
  selector:
    app: service-discovery
