apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: {{ .Values.services.user-service.service.port }}
      targetPort: {{ .Values.services.user-service.service.port }}
  selector:
    app: user-service
