apiVersion: v1
kind: Service
metadata:
  name: zipkin
  labels:
    app: zipkin
spec:
  type: LoadBalancer
  ports:
    - name: "zipkin-port"
      port: {{ .Values.services.zipkin.service.port }}
      targetPort: {{ .Values.services.zipkin.service.port }}
  selector:
    app: zipkin
